name: Deployment

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/meinPrivateKey
          chmod 400 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Ensure Docker is installed on EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo usermod -aG docker ubuntu
            else
              echo "Docker already installed."
            fi
          EOF

      - name: Copy backend and frontend to EC2
        run: |
          scp -i ~/.ssh/meinPrivateKey -r backend ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/
          scp -i ~/.ssh/meinPrivateKey -r frontend ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/

      - name: Build and run Docker containers on EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ubuntu

            # Stop and remove existing containers
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true

            # Build backend image and run container
            cd backend
            docker build -t backend-image .
            docker run -d --name backend -p 5000:5000 backend-image
            cd ..

            # Build frontend image and run container
            cd frontend
            docker build -t frontend-image .
            docker run -d --name frontend -p 80:3000 frontend-image
            cd ..
          EOF
